<?php


namespace App\bigbluebutton\tests;
use BigBlueButton\TestCase as BaseTestCase;

class TestCase extends  BaseTestCase
{
    public function generateCreateParams()
    {


        $arr =  parent::generateCreateParams();

        $arr['guestPolicy'] = 'ALWAYS_ACCEPT';

        return $arr;


          // TODO: Change the autogenerated stub
    }

}