<?php


namespace App\bigbluebutton\tests\Parameters;
use BigBlueButton\Parameters\CreateMeetingParametersTest as BaseCreateMeetingParametersTest;
use App\bigbluebutton\src\Parameters\CreateMeetingParameters;
use App\bigbluebutton\tests\TestCase;

class CreateMeetingParametersTest extends BaseCreateMeetingParametersTest
{
    public function testCreateMeetingParameters()
    {
        $params      = new TestCase();
        $params = $params->generateCreateParams();
        $createMeetingParams = new CreateMeetingParameters($params['meetingId'], $params['meetingName']);
        $this->assertEquals($params['guestPolicy'], $createMeetingParams->getGuestPolicy());
        parent::testCreateMeetingParameters(); // TODO: Change the autogenerated stub
    }

}